[2020-04-17 22:35:43,825: INFO/MainProcess] Received task: celery_tasks.pub_tasks.tasks.clamavfile[590ac1fe-4608-4c37-8614-78d1243d5a2a]  
[2020-04-17 22:35:43,831: INFO/MainProcess] Task celery_tasks.pub_tasks.tasks.clamavfile[590ac1fe-4608-4c37-8614-78d1243d5a2a] succeeded in 0.00492873799521476s: [{'ip': '47.92.255.39', 'status': 'failed', 'version': '', 'connstr': '47.92.255.39 Could not reach clamd using network (47.92.255.39, 3310)', 'scanresult': ''}]
[2020-04-17 22:37:23,606: INFO/MainProcess] Received task: celery_tasks.pub_tasks.tasks.multi_clamd[3eedbee4-4810-4218-9798-f6831da93644]  
[2020-04-17 22:43:45,407: INFO/MainProcess] Task celery_tasks.pub_tasks.tasks.multi_clamd[3eedbee4-4810-4218-9798-f6831da93644] succeeded in 381.8003362270247s: [{'ip': '192.168.27.128', 'status': 'failed', 'version': '', 'connstr': '192.168.27.128 Could not reach clamd using network (192.168.27.128, 3310)', 'scanresult': ''}, {'ip': '172.31.50.138', 'status': 'failed', 'version': '', 'connstr': '172.31.50.138 Could not reach clamd using network (172.31.50.138, 3310)', 'scanresult': ''}, {'ip': '127.0.0.1', 'status': 'failed', 'version': '', 'connstr': '127.0.0.1 Could not reach clamd using network (127.0.0.1, 3310)', 'scanresult': ''}]
